### ISSUE TITLE
公司项目使用的一个库，居然连个文档都没有

### ISSUE THREAD

**Issue by 52lemon** [felinx/djinn#34]
公司项目使用的一个库，居然连个文档都没有，也没有人来讲讲如何使用,能补一个文档吗

**Comment by felinx** [comment]
这个本来是自用的一个库，没想到有人用，文档确实没提供，你可以参考一下另一个项目d3status，虽然没有用到djinn，但是他是djinn的前身，且是个demo程序

**Comment by 52lemon** [comment]
> 这个本来是自用的一个库，没想到有人用，文档确实没提供，你可以参考一下另一个项目d3status，虽然没有用到djinn，但是他是djinn的前身，且是个demo程序

非常感谢

**Comment by felinx** [comment]
这个库很小很简单，你也可以看看你们公司用到的地方是怎么用的 :)
